packages:
  - '.'
  - '../keyboard'

blockExoticSubdeps: true
engineStrict: true
minimumReleaseAge: 10080
minimumReleaseAgeIgnoreMissingTime: false
minimumReleaseAgeStrict: true

allowBuilds:
  esbuild: true
